name: Build & Release

on:
  push:
    tags:
      - '*'

jobs:
  release:
    if: github.repository == 'Protofy-xyz/Vento'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '21'
          # cache: 'yarn'

      - name: Install dependencies
        run: yarn

      - name: Prepare dev
        run: yarn prepare-dev

      - name: Shrink
        run: yarn shrink

      - name: Create release zip
        run: |
          zip -r release-${{ github.ref_name }}.zip . -x ".git/*" "node_modules/*" "release-*.zip"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: release-${{ github.ref_name }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
